name: Build EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller openpyxl

    - name: Build EXE
      run: |
        pyinstaller --onefile add_record.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: add_record_exe
        path: dist/add_record.exe
